backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "/static/img"

collections:
  # --------------------------------------
  # 1. Static Pages
  # --------------------------------------
  - name: "pages"
    label: "Static Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Body", name: "body", widget: "code", default_language: "html" }

      - label: "About Us"
        name: "about"
        file: "about-us/index.html"
        fields:
          - { label: "Body", name: "body", widget: "code", default_language: "html" }

      - label: "Contact Us"
        name: "contact"
        file: "contact-us/index.html"
        fields:
          - { label: "Body", name: "body", widget: "code", default_language: "html" }

      - label: "Blogs"
        name: "blogs"
        file: "blogs/index.html"
        fields:
          - { label: "Body", name: "body", widget: "code", default_language: "html" }

      - label: "Discounted"
        name: "discounted"
        file: "discounted-exam-vouchers/index.html"
        fields:
          - { label: "Body", name: "body", widget: "code", default_language: "html" }

  # --------------------------------------
  # 2. Blog Posts (each in its own folder)
  # --------------------------------------
  - name: "blogs"
    label: "Blogs"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "html"
    format: "frontmatter"
    media_folder: "static/img/blog/{{slug}}"
    public_folder: "/static/img/blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "code", default_language: "html" }

  # --------------------------------------
  # 3. Certifications - Top-level only
  # --------------------------------------
  - name: "certifications"
    label: "Certifications"
    folder: "certifications"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    extension: "html"
    format: "frontmatter"
    media_folder: "static/img/certifications/{{slug}}"
    public_folder: "/static/img/certifications/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "code", default_language: "html" }
