backend:
  name: git-gateway
  identity_url: https://certmatrix.netlify.app/.netlify/identity
  login: true

media_folder: "static/uploads"  # Where uploaded files go in the repo
public_folder: "/uploads"       # How they are accessed in the frontend

media_library:
  name: uploadcare

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
